export const IS_LOADING = 'IS_LOADING';
export const STORE_DATA = 'STORE_DATA';
export const IS_ERROR = 'IS_ERROR'

export const CURRENT_PRODUCT_LOADING = 'CURRENT_LOADING'
export const CURRENT_PRODUCT_DATA = 'CURRENT_PRODUCT_DATA'
export const CURRENT_PRODUCT_ERROR = 'CURRENT_PRODUCT_ERROR'